add lecture05.md
tetsu-git2111/RaiseTech pull request #5
Opened 2023-12-17 13:17 UTC by tetsu-git2111

ご確認お願いいたします。

2023-12-17 14:25 UTC, MasatoshiMizumoto requested changes
画像が報告の書類から見えないので一旦そちらのご対応お願いします！！

2023-12-17 14:25 UTC, MasatoshiMizumoto commented on lecture05.md
画像の埋め込みが軒並みデッドリンクなので、`./`を追記してみてもらえますか？

2023-12-18 09:37 UTC, tetsu-git2111 commented
ご確認ありがとうございます。
画像を見れるようにしました。
再度ご確認お願いいたします。

2023-12-18 09:39 UTC, MasatoshiMizumoto approved these changes
良さそうです！
LGTM!

2023-12-18 12:48 UTC, merged